"""add_multi_tenancy_support

Revision ID: ea3c4d930566
Revises: a1b2c3d4e5f6_token_usage
Create Date: 2025-11-19 11:41:24.197949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3c4d930566'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6_token_usage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_created', 'tenants', ['created_at'], unique=False)
    op.create_index('ix_tenant_slug', 'tenants', ['slug'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('api_keys', sa.Column('tenant_id', app.models.GUID(), nullable=False))
    op.alter_column('api_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.alter_column('api_keys', 'customer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'tenants', ['tenant_id'], ['id'])
    op.add_column('audit_logs', sa.Column('tenant_id', app.models.GUID(), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'api_key_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('customers', sa.Column('tenant_id', app.models.GUID(), nullable=False))
    op.alter_column('customers', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'])
    op.add_column('token_usage', sa.Column('tenant_id', app.models.GUID(), nullable=False))
    op.alter_column('token_usage', 'request_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.alter_column('token_usage', 'api_key_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_token_usage_request_id'), table_name='token_usage')
    op.create_index(op.f('ix_token_usage_request_id'), 'token_usage', ['request_id'], unique=True)
    op.create_index(op.f('ix_token_usage_tenant_id'), 'token_usage', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'token_usage', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_usage', type_='foreignkey')
    op.drop_index(op.f('ix_token_usage_tenant_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_request_id'), table_name='token_usage')
    op.create_index(op.f('ix_token_usage_request_id'), 'token_usage', ['request_id'], unique=False)
    op.alter_column('token_usage', 'api_key_id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('token_usage', 'request_id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('token_usage', 'tenant_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.alter_column('customers', 'id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('customers', 'tenant_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'api_key_id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'request_id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.alter_column('api_keys', 'customer_id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=app.models.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('api_keys', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('ix_tenant_slug', table_name='tenants')
    op.drop_index('ix_tenant_created', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
